##### Menu
menu:
  首页: /
  归档: /archives
  关于: /about
  
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- tagcloud
- rss
- cc
- links
- recent_visitors
- recent_comments

## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo
## modify links in `/layout/_widget/links.ejs`.

#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: false             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     

#### Author Avatar Picture
author_img_enable: false ## display author avatar picture
dataURI: false
## if the picture's format is dataURI please set the value to true,otherwise set the value to false.
## convert an image into base 64 data URIs http://websemantics.co.uk/online_tools/image_to_data_uri_convertor/ .
author_img_data: 
## paste the dataURI in ONE LINE and included it by ''.
author_img: img/author.jpg ## size:220px*220px.
## if the picture's format is `.png` or `.jpg`  instead of dataURI,you should set the `dataURI` value to false.

#### Font
ShowCustomFont: true  
## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Fancybox
fancybox: true 
## if you use gallery post or want use fancybox please set the value to true.
## if you want use fancybox in ANY post please copy the file `fancybox.js`.
## in theme folder `/jacman/scripts` to your hexo blog folder `../scritps`.

### Scroll to top
totop: true   ##show scroll-to-top in article
##if you want to scroll to top in every post set the value to true

#### Author information
author:
  intro_line1:  ""  ## eg: "Hello ,I'm Larry Page in Google."
  intro_line2:  ""  ## eg: "This is my blog,believe it or not."
  v2ex: lcj2class
  zhihu: jiacai2050
  weibo: liujiacai     ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  twitter: liujiacai    ## e.g. wuchong for https://twitter.com/wuchong
  github: jiacai2050    ## e.g. wuchong for https://github.com/wuchong
  facebook: liujiacai  ## e.g. wuchong for https://facebook.com/wuchong
  douban: liujiacai    ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  tsina: 608384123     ## e.g. 2176287895  Your weibo ID,It will be used in share button.
  stackoverflow: 2163429 ##3222790   ##e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
  email:      ## e.g. wuchong1014@gmail.com
  google_plus:    ## eg:111190881341800841449 for https://plus.google.com/u/0/111190881341800841449
## if you set them, the corresponding  share button will show on the footer
 

#### Comment
duoshuo: 
  enable: true  ## duoshuo.com
  short_name: jiacai2050   ##e.g. wuchong   for duoshuo short name.

disqus:
  enable: false  ## disqus.com
  short_name:    ##e.g. wuchong   for disqus short name.  

#### Share button
jiathis:
  enable: true ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id: 1567950  ## e.g. 1567950 your jiathis ID. 
  tsina: 608384123  ## e.g.  Your weibo id,It will be used in share button.

#### Custom Search
google:
  enable: true  
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
  
  
#### Analytics
baidu_analytics:
  enable: true